name: deployment-production

on:
  push:
    branches:
      - master

jobs:
  deployment-production:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v2
      - name: Deploy using SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: 22
          script: |
            cd /var/www/belajar-git.cloud/html
            git pull origin master
